package com.geishatokyo.sqltool.mysql

import org.specs2.mutable.Specification

/**
 * 
 * User: takeshita
 * DateTime: 13/05/29 11:12
 */
class CreateTableParserTest extends Specification {


  "Simple sql" should{
    "mix lower and upper cases" in {
      val sql = "CreaTe Table IF Not exists hoge(" +
        "id Int primary key );"

      val table = CreateTableParser(sql)
      table.name must_== "hoge"

    }
  }

  "Variable sql type" should{

    val sqlGeneratedByMySQLServer =
      """
        |CREATE TABLE `itemdata` (
        |  `itemId` bigint(20) NOT NULL,
        |  `itemType` int(11) NOT NULL,
        |  `name` varchar(100) CHARACTER SET utf8mb4 NOT NULL,
        |  `thumbnail` varchar(100) CHARACTER SET utf8mb4 NOT NULL,
        |  `explanation` longtext CHARACTER SET utf8mb4 NOT NULL,
        |  `created` datetime NOT NULL,
        |  `updated` datetime NOT NULL,
        |  PRIMARY KEY (`itemId`)
        |) ENGINE=InnoDB DEFAULT CHARSET=utf8
      """.stripMargin


    "parse create table sql generated by MySQL server" in{

      val tableDef = CreateTableParser(sqlGeneratedByMySQLServer)

      tableDef.name must_== "itemdata"

      tableDef.column("itemId") must_== Column("itemId","bigint(20)",List(NotNull()))
      tableDef.column("itemType") must_== Column("itemType","int(11)",List(NotNull()))
      tableDef.column("name") must_== Column("name","varchar(100)",List(CharacterSet("utf8mb4"), NotNull()))
      tableDef.column("thumbnail") must_== Column("thumbnail","varchar(100)",List(CharacterSet("utf8mb4"), NotNull()))
      tableDef.column("explanation") must_== Column("explanation","longtext",List(CharacterSet("utf8mb4"), NotNull()))
      tableDef.column("created") must_== Column("created","datetime",List(NotNull()))
      tableDef.column("updated") must_== Column("updated","datetime",List(NotNull()))

      tableDef.primaryKey must_== Some(PrimaryKey(List("itemId")))

    }

    val sqlGeneratedByMySQLServer2 =
      """
        |CREATE TABLE `friendlink` (
        |  `id` bigint(20) NOT NULL AUTO_INCREMENT,
        |  `ownerId` bigint(20) NOT NULL,
        |  `friendId` bigint(20) NOT NULL,
        |  `status` int(11) NOT NULL,
        |  `friendship` int(11) NOT NULL,
        |  `updated` datetime NOT NULL,
        |  PRIMARY KEY (`id`)
        |) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8
      """.stripMargin

     "parse create table sql2 generated by MySQL server" in{

      val tableDef = CreateTableParser(sqlGeneratedByMySQLServer2)

      tableDef.name must_== "friendlink"

      tableDef.column("id") must_== Column("id","bigint(20)",List(NotNull(),AutoIncrement()))
      tableDef.column("ownerId") must_== Column("ownerId","bigint(20)",List(NotNull()))
      tableDef.column("friendId") must_== Column("friendId","bigint(20)",List(NotNull()))
      tableDef.column("status") must_== Column("status","int(11)",List(NotNull()))
      tableDef.column("friendship") must_== Column("friendship","int(11)",List(NotNull()))
      tableDef.column("updated") must_== Column("updated","datetime",List(NotNull()))

      tableDef.primaryKey must_== Some(PrimaryKey(List("id")))

    }
  }



}
